# -*- coding: utf-8 -*-
"""euclidean_calculus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_9wb9mLbAcJu2ekFNul-VIEpTr1UPP8y
"""

import math

points = [(0, 0), (3, 2), (5, 4), (7, 5)]

def euclideanDistance(p1, p2):
    x1, y1 = p1
    x2, y2 = p2
    return math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)

distances = []
for i in range(len(points)):
    for j in range(i + 1, len(points)):
        distance = euclideanDistance(points[i], points[j])
        distances.append(distance)

min_distance = min(distances)

print("Min distance:", min_distance)